// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/_utils/request-context': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/_utils/request-context').default>>>>
    }
    '/api/v1/admin/dashboard': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/admin/dashboard/index.get').default>>>>
    }
    '/api/v1/admin/entries/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/admin/entries/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/admin/entries/[id].get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/admin/entries/[id].patch').default>>>>
    }
    '/api/v1/admin/entries': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/admin/entries/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/admin/entries/index.post').default>>>>
    }
    '/api/v1/admin/invites/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/admin/invites/[id].delete').default>>>>
    }
    '/api/v1/admin/invites/:id/accept': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/admin/invites/[id]/accept.post').default>>>>
    }
    '/api/v1/admin/invites': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/admin/invites/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/admin/invites/index.post').default>>>>
    }
    '/api/v1/admin/media/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/admin/media/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/admin/media/[id].get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/admin/media/[id].patch').default>>>>
    }
    '/api/v1/admin/media': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/admin/media/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/admin/media/index.post').default>>>>
    }
    '/api/v1/admin/models/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/admin/models/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/admin/models/[id].get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/admin/models/[id].patch').default>>>>
    }
    '/api/v1/admin/models': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/admin/models/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/admin/models/index.post').default>>>>
    }
    '/api/v1/admin/projects/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/admin/projects/[id].get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/admin/projects/[id].patch').default>>>>
    }
    '/api/v1/admin/projects/:id/switch': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/admin/projects/[id]/switch.post').default>>>>
    }
    '/api/v1/admin/projects': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/admin/projects/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/admin/projects/index.post').default>>>>
    }
    '/api/v1/admin/tokens/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/admin/tokens/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/admin/tokens/[id].get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/admin/tokens/[id].patch').default>>>>
    }
    '/api/v1/admin/tokens': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/admin/tokens/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/admin/tokens/index.post').default>>>>
    }
    '/api/v1/admin/webhooks/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/admin/webhooks/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/admin/webhooks/[id].patch').default>>>>
    }
    '/api/v1/admin/webhooks/:id/deliver': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/admin/webhooks/[id]/deliver.post').default>>>>
    }
    '/api/v1/admin/webhooks': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/admin/webhooks/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/admin/webhooks/index.post').default>>>>
    }
    '/api/v1/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/auth/login.post').default>>>>
    }
    '/api/v1/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/auth/logout.post').default>>>>
    }
    '/api/v1/auth/options': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/auth/options.get').default>>>>
    }
    '/api/v1/auth/session': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/auth/session.get').default>>>>
    }
    '/api/v1/content/:modelApiId/:entryId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/content/[modelApiId]/[entryId].get').default>>>>
    }
    '/api/v1/content/:modelApiId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/content/[modelApiId]/index.get').default>>>>
    }
    '/api/v1/invites/:token/accept': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/invites/[token]/accept.post').default>>>>
    }
    '/api/v1/media/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/media/[id].get').default>>>>
    }
    '/api/v1/media': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/media/index.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
  }
}
export {}